export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const FETCH_PACK_LIST = 'FETCH_PACK_LIST';
export const FETCH_PACK_DETAIL = 'FETCH_PACK_DETAIL';
export const RESET_FETCH_PACK_DETAIL = 'RESET_FETCH_PACK_DETAIL';
export const APPLY_PROMO_CODE = 'APPLY_PROMO_CODE';
export const CREATE_ORDER = 'CREATE_ORDER';