export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const FETCH_PROFILE = "FETCH_PROFILE";
export const FETCH_TIME_SCHEDULE_CONFIGURATION = "FETCH_TIME_SCHEDULE_CONFIGURATION";
export const STORE_TIME_SCHEDULE_CONFIGURATION = "STORE_TIME_SCHEDULE_CONFIGURATION";
